# Generated by Django 5.2.15 on 2026-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("transfer", "Transfer Bank"), ("cash", "Cash")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Belum Dibayar"),
                    ("waiting", "Menunggu Verifikasi"),
                    ("approved", "Disetujui"),
                    ("rejected", "Ditolak"),
                    ("cancelled", "Dibatalkan"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
