# Generated by Django 5.2.15 on 2026-07-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_product_slug"),
        ("rentals", "0002_rentalitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_items",
                to="catalog.product",
                verbose_name="Produk",
            ),
        ),
    ]
