# Generated by Django 5.2.15 on 2026-07-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_category_description_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nama Produk")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Merek"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Harga / Hari"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stok")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Foto Produk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
    ]
