# Generated by Django 5.2.15 on 2026-07-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="Slug"),
        ),
    ]
